name: Plugin Tests

on: [ push, pull_request ]

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [12.x, 14.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Plugin
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: Compile grammar
      run: npm run grammar

    - name: Run test suite
      run: npm run test

      env:
        CI: true
