on: [ pull_request ]

name: Test Coverage

jobs:

  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      name: Checkout Plugin
      with:
        fetch-depth: 1

    - name: Use Node.js 14
      uses: actions/setup-node@master
      with:
        node-version: 14

    - name: install, run
      run: |
        npm install
        npm install --no-save nyc codecov
        npm run cover

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
